export const INITIAL_REDUCER = 'INITIAL_REDUCER';
export const CATEGORY_SEARCH = 'CATEGORY_SEARCH';
export const ADD_USER = 'ADD_USER';
export const ADD_REG_ERROR = 'ADD_REG_ERROR';
export const ADD_LOG_ERROR = 'ADD_LOG_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const VIEW_VOLUME = 'VIEW_VOLUME';
